# Generated by Django 4.2.7 on 2025-10-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the material.', max_length=100)),
                ('image_swatch', models.ImageField(blank=True, help_text='Visual swatch for material selection.', null=True, upload_to='swatches/')),
                ('material_cost_per_sqft', models.DecimalField(decimal_places=4, help_text='Raw material cost for pricing (per sqft).', max_digits=10)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(null=True, upload_to='gallery/')),
                ('role', models.CharField(max_length=50, null=True)),
                ('caption', models.CharField(max_length=255, null=True)),
                ('display_order', models.IntegerField()),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.material')),
            ],
            options={
                'unique_together': {('material', 'role')},
            },
        ),
        migrations.CreateModel(
            name='CustomizationField',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField()),
                ('display_order', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.material')),
            ],
            options={
                'unique_together': {('material', 'field_name')},
            },
        ),
    ]
