# Generated by Django 4.2.7 on 2025-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_material_productimage_customizationfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationfield',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customizationfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customizationfield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
