# Generated by Django 4.2.7 on 2025-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_customizationfield_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_types/'),
        ),
    ]
