# Generated by Django 4.2.7 on 2025-10-21 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0005_producttype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('width_inches', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height_inches', models.DecimalField(decimal_places=2, max_digits=6)),
                ('config_details', models.JSONField()),
                ('calculated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.material')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.producttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='field_options/')),
                ('price_modifier_flat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_modifier_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('option_data', models.JSONField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.customizationfield')),
            ],
        ),
    ]
