# Generated by Django 4.2.7 on 2025-10-23 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_productconfiguration_fieldoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product title shown on card.', max_length=100)),
                ('badge', models.CharField(blank=True, help_text="Optional label like 'Best Sale', 'Sale 50%', 'Top Rated', etc.", max_length=50, null=True)),
                ('sale_percentage', models.PositiveIntegerField(default=0, help_text='Discount percentage if any.')),
                ('display_order', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.material')),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_title', models.CharField(help_text='Title shown on the sale card.', max_length=100)),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Discount percentage (e.g., 50 for 50%).')),
                ('start_time', models.DateTimeField(help_text='Sale start time.')),
                ('end_time', models.DateTimeField(help_text='Sale end time.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.material')),
            ],
        ),
    ]
