# Generated by Django 4.2 on 2025-10-27 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_company_department_designation_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='admin_app.menu')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, null=True)),
                ('can_add', models.BooleanField(default=False, null=True)),
                ('can_edit', models.BooleanField(default=False, null=True)),
                ('can_delete', models.BooleanField(default=False, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.menu')),
                ('submenu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.submenu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
