# Generated by Django 4.2 on 2025-10-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_menu_submenu_submenupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.submenu')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'submenu')},
            },
        ),
        migrations.DeleteModel(
            name='SubMenuPermission',
        ),
    ]
